# Generated by Django 3.0.3 on 2023-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='profile_picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
