# Generated by Django 3.0.3 on 2023-07-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230714_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpic',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
