# Generated by Django 3.0.3 on 2023-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230714_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
