# Generated by Django 3.0.3 on 2023-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230714_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmation',
            name='file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
