# Generated by Django 3.0.3 on 2023-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderconfirmation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
