# Generated by Django 3.0.3 on 2023-07-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230714_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
