# Generated by Django 3.0.3 on 2023-07-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230714_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='leiras',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
