# Generated by Django 4.2.4 on 2023-12-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
