# Generated by Django 4.2.4 on 2023-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_leiras_sr_product_namesr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='namesr',
        ),
        migrations.AddField(
            model_name='product',
            name='serbian_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
