# Generated by Django 4.2.4 on 2023-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_namesr_product_serbian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serbian_name',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
