# Generated by Django 4.2.4 on 2023-12-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_serbian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serbian_name',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
    ]
