# Generated by Django 4.2.4 on 2023-12-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_serbian_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serbian_name',
            new_name='name2',
        ),
    ]
