# Generated by Django 4.2.4 on 2024-01-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_serbian_name_product_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
